'use client'

import { useEffect, useState } from 'react'

interface ReportData {
  datasetLabel: string
  metrics: {
    conversationVolume: number
    inboundDemandRate: number
    responseTimeMedianMinutes: number
    commercialIntentRate: number
    priceInquiryRate: number
    bookingIntentRate: number
    conversionRate: number
    ghostRate: number
    repeatClientRate: number
    estimatedRevenueLow: number
    estimatedRevenueHigh: number
  }
  ledger: Array<{
    id: string
    clientHash: string
    firstSeen: string
    lastSeen: string
    inboundCount: number
    outboundCount: number
    responseTimeMedianMinutes: number
    bookingIntent: boolean
    confirmedProxy: boolean
    repeatClient: boolean
    estimatedValueBand: string
  }>
  privacyReceipt: {
    rawMessagesProcessed: boolean
    identitiesExposed: boolean
    fieldsExported: string[]
    method: string
  }
}

const PIPELINE = [
  ['Synthetic conversations', 'Fabricated message threads stand in for a real client history.'],
  ['Commercial-intent tagging', 'Each thread is scored for price, availability, and location asks.'],
  ['Conversion-density metrics', 'Thread-level tags are rolled up into aggregate demand KPIs.'],
  ['Anonymized demand report', 'Only hashed IDs and counts leave the pipeline — never raw text.']
]

export function DemandLedger() {
  const [data, setData] = useState<ReportData | null>(null)
  const [showReport, setShowReport] = useState(false)

  useEffect(() => {
    fetch('/api/demand-report')
      .then((response) => response.json())
      .then(setData)
  }, [])

  if (!data) {
    return <div className="vault-card">Loading demand ledger...</div>
  }

  const m = data.metrics

  return (
    <div className="demand-shell">
      <div className="demand-banner">
        {data.datasetLabel}. This page never touches a real chat.db, phone number, or client
        identity — every row below is generated by a seeded random function.
      </div>

      <section className="brand-panel demand-intro">
        <p className="eyebrow">CONVERSATIONAL DEMAND ACCOUNTING</p>
        <h2>Demand-flow before cash-flow.</h2>
        <p className="hero-copy">
          Cash-flow underwriting reads a bank account after money moves. This prototype reads
          the conversation that happens before it — inbound interest, pricing questions,
          availability requests, booking intent, and repeat contact — and turns it into
          aggregate, non-identifying metrics.
        </p>

        <div className="cycle-row demand-pipeline">
          {PIPELINE.map(([title, body]) => (
            <div className="cycle-step" key={title}>
              <h3>{title}</h3>
              <p>{body}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="demand-kpi-grid">
        <KpiTile label="Conversation Volume" value={m.conversationVolume} />
        <KpiTile label="Inbound Demand Rate" value={`${m.inboundDemandRate}%`} />
        <KpiTile label="Median Response Time" value={`${m.responseTimeMedianMinutes} min`} />
        <KpiTile label="Commercial Intent Rate" value={`${m.commercialIntentRate}%`} />
        <KpiTile label="Price Inquiry Rate" value={`${m.priceInquiryRate}%`} />
        <KpiTile label="Booking Intent Rate" value={`${m.bookingIntentRate}%`} />
        <KpiTile label="Conversion Rate" value={`${m.conversionRate}%`} />
        <KpiTile label="Ghost Rate" value={`${m.ghostRate}%`} />
        <KpiTile label="Repeat Client Rate" value={`${m.repeatClientRate}%`} />
        <KpiTile
          label="Estimated Revenue Band"
          value={`$${m.estimatedRevenueLow.toLocaleString()}–$${m.estimatedRevenueHigh.toLocaleString()}`}
        />
      </section>

      <section className="brand-panel demand-table-panel">
        <p className="eyebrow">ANONYMIZED DEMAND LEDGER (SYNTHETIC)</p>
        <div className="demand-table-scroll">
          <table className="demand-table">
            <thead>
              <tr>
                <th>Thread</th>
                <th>Client Hash</th>
                <th>First Seen</th>
                <th>Last Seen</th>
                <th>In / Out</th>
                <th>Response</th>
                <th>Booking Intent</th>
                <th>Confirmed</th>
                <th>Repeat</th>
                <th>Value Band</th>
              </tr>
            </thead>
            <tbody>
              {data.ledger.slice(0, 20).map((row) => (
                <tr key={row.id}>
                  <td>{row.id}</td>
                  <td className="mono">{row.clientHash}</td>
                  <td>{row.firstSeen}</td>
                  <td>{row.lastSeen}</td>
                  <td>
                    {row.inboundCount} / {row.outboundCount}
                  </td>
                  <td>{row.responseTimeMedianMinutes}m</td>
                  <td>{row.bookingIntent ? 'Yes' : '—'}</td>
                  <td>{row.confirmedProxy ? 'Yes' : '—'}</td>
                  <td>{row.repeatClient ? 'Yes' : '—'}</td>
                  <td>{row.estimatedValueBand}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <p className="muted demand-table-note">
          Showing 20 of {data.ledger.length} synthetic threads. No message content, names, or
          phone numbers are stored or displayed at any point in this pipeline.
        </p>
      </section>

      <section className="bottom-grid demand-bottom-grid">
        <div className="brand-panel trust-panel">
          <p className="eyebrow">PRIVACY RECEIPT</p>
          <ul>
            <li>Raw messages processed: {data.privacyReceipt.rawMessagesProcessed ? 'Yes' : 'No'}</li>
            <li>Identities exposed: {data.privacyReceipt.identitiesExposed ? 'Yes' : 'No'}</li>
            <li>Fields exported: {data.privacyReceipt.fieldsExported.length}</li>
          </ul>
          <p className="muted" style={{ marginTop: 12 }}>{data.privacyReceipt.method}</p>
        </div>

        <div className="brand-panel demand-report-panel">
          <p className="eyebrow">LENDER-STYLE SUMMARY</p>
          <button className="gold-button" onClick={() => setShowReport((s) => !s)}>
            {showReport ? 'Hide Report' : 'Generate Demand Report'}
          </button>

          {showReport && (
            <pre className="demand-report-text">{`CONVERSATIONAL DEMAND REPORT (SYNTHETIC DEMO)
Dataset: ${data.datasetLabel}

Conversation volume ........ ${m.conversationVolume} threads
Inbound demand rate ........ ${m.inboundDemandRate}%
Median response time ....... ${m.responseTimeMedianMinutes} minutes
Commercial intent rate ..... ${m.commercialIntentRate}%
Price inquiry rate ......... ${m.priceInquiryRate}%
Booking intent rate ........ ${m.bookingIntentRate}%
Conversion rate ............ ${m.conversionRate}%
Ghost rate .................. ${m.ghostRate}%
Repeat client rate ......... ${m.repeatClientRate}%
Estimated revenue band ..... $${m.estimatedRevenueLow.toLocaleString()}–$${m.estimatedRevenueHigh.toLocaleString()}

This report is built entirely from a fabricated demo dataset. It contains
no real client conversations, phone numbers, or identities, and is not
evidence of any real business's demand or revenue.`}</pre>
          )}
        </div>
      </section>
    </div>
  )
}

function KpiTile({ label, value }: { label: string; value: string | number }) {
  return (
    <div className="brand-panel demand-kpi-tile">
      <small>{label}</small>
      <strong>{value}</strong>
    </div>
  )
}
